/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Clases;

import static Clases.Empleados.res;
import Conexiones.Procedimientos;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.SpinnerNumberModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.JInternalFrame;


/**
 *
 * @author mario
 */
public class HacerPedido extends javax.swing.JFrame {

    /**
     * Creates new form HacerPedido
     */
    
   
    
    public HacerPedido() {
        initComponents();
        
        
        
        SpinnerNumberModel modeloSpinner2 = new SpinnerNumberModel();
        modeloSpinner2.setMaximum(300);
        modeloSpinner2.setMinimum(1);
        modeloSpinner2.setStepSize(1);
        modeloSpinner2.setValue(1);
        spnCantidad2.setModel(modeloSpinner2);
    }

    public void mostrarInformacion(ArrayList<String> lista) {	
        DefaultTableModel modelo = (DefaultTableModel) TablaJuegosSeleccionados.getModel();
        modelo.setRowCount(0);    
        for(int i = 0; i < lista.size(); i++){
                mostrarJuegosSeleccionados(TablaJuegosSeleccionados, "SELECT * FROM Vista_Juegos_Disponibles where idJuego = "+ "'" + lista.get(i).toString() + "';");
            }
            
	}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel7 = new javax.swing.JPanel();
        lblHacerPedido = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TablaJuegosSeleccionados = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        lblPlataforma = new javax.swing.JLabel();
        lblPlataforma1 = new javax.swing.JLabel();
        lblPlataforma2 = new javax.swing.JLabel();
        lblPlataforma3 = new javax.swing.JLabel();
        lblPlataforma4 = new javax.swing.JLabel();
        lblPlataforma5 = new javax.swing.JLabel();
        lblPlataforma6 = new javax.swing.JLabel();
        lblPlataforma7 = new javax.swing.JLabel();
        txtColonia = new javax.swing.JTextField();
        txtNumTelefono = new javax.swing.JTextField();
        txtNumTarjeta = new javax.swing.JTextField();
        txtCv = new javax.swing.JTextField();
        txtCalle = new javax.swing.JTextField();
        txtMunicipio = new javax.swing.JTextField();
        cobBanco = new javax.swing.JComboBox<>();
        cobEstado = new javax.swing.JComboBox<>();
        lblPlataforma8 = new javax.swing.JLabel();
        lblPlataforma9 = new javax.swing.JLabel();
        txtJuegoSelecionado = new javax.swing.JTextField();
        spnCantidad2 = new javax.swing.JSpinner();
        btnVender2 = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        txtTotal = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtIDJuego2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel7.setBackground(new java.awt.Color(79, 242, 222));
        jPanel7.setForeground(new java.awt.Color(79, 242, 222));

        lblHacerPedido.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblHacerPedido.setForeground(new java.awt.Color(255, 255, 255));
        lblHacerPedido.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHacerPedido.setText("Hacer pedido");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblHacerPedido)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblHacerPedido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        TablaJuegosSeleccionados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "IDJuego", "Titulo", "Genero", "Estudio", "Plataforma", "Cantidad", "Precio"
            }
        ));
        TablaJuegosSeleccionados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaJuegosSeleccionadosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TablaJuegosSeleccionados);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lblPlataforma.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        lblPlataforma.setText("Estado:");

        lblPlataforma1.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        lblPlataforma1.setText("Municipio:");

        lblPlataforma2.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        lblPlataforma2.setText("Colonia:");

        lblPlataforma3.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        lblPlataforma3.setText("Num. Telefono:");

        lblPlataforma4.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        lblPlataforma4.setText("Calle y numero:");

        lblPlataforma5.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        lblPlataforma5.setText("Banco:");

        lblPlataforma6.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        lblPlataforma6.setText("Num. Tarjeta:");

        lblPlataforma7.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        lblPlataforma7.setText("Cv:");

        txtColonia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtColoniaActionPerformed(evt);
            }
        });

        txtNumTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumTelefonoActionPerformed(evt);
            }
        });
        txtNumTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNumTelefonoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNumTelefonoKeyTyped(evt);
            }
        });

        txtNumTarjeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumTarjetaActionPerformed(evt);
            }
        });
        txtNumTarjeta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNumTarjetaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNumTarjetaKeyTyped(evt);
            }
        });

        txtCv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCvActionPerformed(evt);
            }
        });
        txtCv.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCvKeyTyped(evt);
            }
        });

        txtCalle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCalleActionPerformed(evt);
            }
        });

        txtMunicipio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMunicipioActionPerformed(evt);
            }
        });
        txtMunicipio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMunicipioKeyTyped(evt);
            }
        });

        cobBanco.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona un banco...", "Bancomer", "Banorte", "Banamex", "Banco azteca", "Santander" }));

        cobEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona un estado...", "Aguascalientes", "Chihuahua", "Ciudad de México", "Guanajuato", "Yucatán", "Zacatecas" }));

        lblPlataforma8.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        lblPlataforma8.setText("Juego Seleccionado:");

        lblPlataforma9.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        lblPlataforma9.setText("Cantidad:");

        txtJuegoSelecionado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtJuegoSelecionadoMouseClicked(evt);
            }
        });
        txtJuegoSelecionado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJuegoSelecionadoActionPerformed(evt);
            }
        });
        txtJuegoSelecionado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtJuegoSelecionadoKeyReleased(evt);
            }
        });

        spnCantidad2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spnCantidad2StateChanged(evt);
            }
        });
        spnCantidad2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                spnCantidad2MouseClicked(evt);
            }
        });
        spnCantidad2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                spnCantidad2KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                spnCantidad2KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                spnCantidad2KeyTyped(evt);
            }
        });

        btnVender2.setText("Comprar");
        btnVender2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVender2ActionPerformed(evt);
            }
        });

        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        jLabel1.setText("Total:");

        txtIDJuego2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtIDJuego2KeyReleased(evt);
            }
        });

        jLabel2.setText("IDJuedo:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnRegresar)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(88, 88, 88)
                                .addComponent(txtCalle, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(txtIDJuego2))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtJuegoSelecionado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblPlataforma8)
                                        .addGap(19, 19, 19)))))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cobBanco, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCv, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(spnCantidad2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(29, 29, 29))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblPlataforma9)
                                        .addGap(63, 63, 63)
                                        .addComponent(jLabel1)
                                        .addGap(70, 70, 70)))
                                .addComponent(btnVender2, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblPlataforma)
                                .addGap(129, 129, 129)
                                .addComponent(lblPlataforma2))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtMunicipio, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                                        .addComponent(cobEstado, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(lblPlataforma1))
                                .addGap(20, 20, 20)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtColonia, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblPlataforma4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNumTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblPlataforma3)
                                    .addComponent(lblPlataforma5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblPlataforma6)
                                    .addComponent(txtNumTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblPlataforma7))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPlataforma)
                    .addComponent(lblPlataforma2)
                    .addComponent(lblPlataforma3)
                    .addComponent(lblPlataforma6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtColonia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNumTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNumTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cobEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRegresar)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPlataforma4)
                            .addComponent(lblPlataforma1)
                            .addComponent(lblPlataforma5)
                            .addComponent(lblPlataforma7))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtCv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtMunicipio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cobBanco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(33, 33, 33)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(lblPlataforma9)
                                    .addComponent(lblPlataforma8)
                                    .addComponent(jLabel2))
                                .addGap(25, 25, 25)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(spnCantidad2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtJuegoSelecionado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtIDJuego2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(33, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnVender2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(48, 48, 48))))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane2)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtColoniaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtColoniaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtColoniaActionPerformed

    private void txtNumTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumTelefonoActionPerformed

    private void txtNumTarjetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumTarjetaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumTarjetaActionPerformed

    private void txtCvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCvActionPerformed

    private void txtCalleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCalleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCalleActionPerformed

    private void txtMunicipioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMunicipioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMunicipioActionPerformed

    private void txtJuegoSelecionadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJuegoSelecionadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJuegoSelecionadoActionPerformed

    private void btnVender2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVender2ActionPerformed
        try{
            if(cobEstado.getSelectedItem().equals("Selecciona un estado...")){
                JOptionPane.showMessageDialog(this, "No olvides seleccionar tu estado", "Atencion!!!!", JOptionPane.INFORMATION_MESSAGE);
            }else if(txtMunicipio.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "No olvides ingresar tu municipio", "Atencion!!!!", JOptionPane.INFORMATION_MESSAGE);
            }else if(txtColonia.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "No olvides ingresar tu colonia", "Atencion!!!!", JOptionPane.INFORMATION_MESSAGE);
            }else if(txtCalle.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "No olvides ingresar tu calle", "Atencion!!!!", JOptionPane.INFORMATION_MESSAGE);
            }else if(txtNumTelefono.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "No olvides ingresar tu numero de telefono", "Atencion!!!!", JOptionPane.INFORMATION_MESSAGE);
            }else if(cobBanco.getSelectedItem().equals("Selecciona un banco...")){
                JOptionPane.showMessageDialog(this, "No olvides seleccionar tu estado", "Atencion!!!!", JOptionPane.INFORMATION_MESSAGE);
            }else if(txtNumTarjeta.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "No olvides ingresar el numero de tu tarjeta", "Atencion!!!!", JOptionPane.INFORMATION_MESSAGE);
            }else if(txtCv.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "No olvides ingresar tu codigo CV", "Atencion!!!!", JOptionPane.INFORMATION_MESSAGE);
            }else if(txtJuegoSelecionado.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "No olvides ingresar seleccionar un juego", "Atencion!!!!", JOptionPane.INFORMATION_MESSAGE);
            }else if(txtNumTelefono.getText().length()>10){
                JOptionPane.showMessageDialog(this, "Ingresaste mas de 10 numeros en el numero de telefono", "Atencion!!!!", JOptionPane.INFORMATION_MESSAGE);
            }else if(txtNumTarjeta.getText().length()>10){
                JOptionPane.showMessageDialog(this, "Ingresaste mas de 16 numeros en el numero de tarjeta", "Atencion!!!!", JOptionPane.INFORMATION_MESSAGE);
            }else if(txtCv.getText().length()>3){
                JOptionPane.showMessageDialog(this, "Ingresaste mas de 10 numeros en el numero de CV", "Atencion!!!!", JOptionPane.INFORMATION_MESSAGE);
            }else{
                Procedimientos.ventaJuego(Integer.parseInt(spnCantidad2.getValue().toString()), cobEstado.getSelectedItem().toString(), txtMunicipio.getText(), txtColonia.getText(), txtCalle.getText(), txtNumTelefono.getText(), 
                        cobBanco.getSelectedItem().toString(), txtNumTarjeta.getText(), txtCv.getText(), 0, txtIDJuego2.getText(), txtJuegoSelecionado.getText(), 0, "JC");
                
                txtIDJuego2.setText("");
                txtJuegoSelecionado.setText("");
                txtTotal.setText("");
                spnCantidad2.setValue(1);
                        
                JOptionPane.showMessageDialog(this, "Gracias por comprar!!!");
        }
        }catch(SQLException e){
            
        }
    }//GEN-LAST:event_btnVender2ActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void TablaJuegosSeleccionadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaJuegosSeleccionadosMouseClicked
        txtJuegoSelecionado.setText("");
        txtIDJuego2.setText("");
        
        int col = TablaJuegosSeleccionados.getSelectedRow();
        txtIDJuego2.setText(TablaJuegosSeleccionados.getValueAt(col, 0).toString());
        txtJuegoSelecionado.setText(TablaJuegosSeleccionados.getValueAt(col, 1).toString());
        txtTotal.setText(TablaJuegosSeleccionados.getValueAt(col, 6).toString());
    }//GEN-LAST:event_TablaJuegosSeleccionadosMouseClicked

    private void txtIDJuego2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIDJuego2KeyReleased
        
    }//GEN-LAST:event_txtIDJuego2KeyReleased

    private void txtJuegoSelecionadoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtJuegoSelecionadoKeyReleased
  
    }//GEN-LAST:event_txtJuegoSelecionadoKeyReleased

    private void txtJuegoSelecionadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtJuegoSelecionadoMouseClicked
        
        
    }//GEN-LAST:event_txtJuegoSelecionadoMouseClicked

    private void spnCantidad2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_spnCantidad2KeyPressed
        
    }//GEN-LAST:event_spnCantidad2KeyPressed

    private void spnCantidad2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_spnCantidad2KeyReleased
        
    }//GEN-LAST:event_spnCantidad2KeyReleased

    private void spnCantidad2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_spnCantidad2KeyTyped
        
    }//GEN-LAST:event_spnCantidad2KeyTyped

    private void spnCantidad2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_spnCantidad2MouseClicked
        
    }//GEN-LAST:event_spnCantidad2MouseClicked

    private void spnCantidad2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spnCantidad2StateChanged
        
    }//GEN-LAST:event_spnCantidad2StateChanged

    private void txtNumTelefonoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumTelefonoKeyPressed
          
    }//GEN-LAST:event_txtNumTelefonoKeyPressed

    private void txtNumTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumTelefonoKeyTyped
        char car = evt.getKeyChar();
        if((car < '0' || car > '9')) evt.consume();
    }//GEN-LAST:event_txtNumTelefonoKeyTyped

    private void txtNumTarjetaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumTarjetaKeyPressed
        
    }//GEN-LAST:event_txtNumTarjetaKeyPressed

    private void txtNumTarjetaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumTarjetaKeyTyped
        char car = evt.getKeyChar();
        if((car < '0' || car > '9')) evt.consume();
    }//GEN-LAST:event_txtNumTarjetaKeyTyped

    private void txtCvKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCvKeyTyped
        char car = evt.getKeyChar();
        if((car < '0' || car > '9')) evt.consume();
    }//GEN-LAST:event_txtCvKeyTyped

    private void txtMunicipioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMunicipioKeyTyped
        char validar = evt.getKeyChar();
        
        if(Character.isDigit(validar)){
            getToolkit().beep();
            evt.consume();
            
            JOptionPane.showMessageDialog(rootPane, "Ingresa solamente letras");
        }
    }//GEN-LAST:event_txtMunicipioKeyTyped

    
    static ResultSet res; 
    
    public void mostrarJuegosSeleccionados(JTable tabla,String com){
        DefaultTableModel modelo = (DefaultTableModel) tabla.getModel();
        res=Conexiones.Conexion.Consulta(com);
        try {
            
            while(res.next()){
                Vector v = new Vector();
                v.add(res.getString(1));
                v.add(res.getString(2));
                v.add(res.getString(3));
                v.add(res.getString(4));
                v.add(res.getString(5));
                v.add(res.getInt(6));
                v.add(res.getDouble(7));
                modelo.addRow(v);
                tabla.setModel(modelo);
            }
                
        } catch (Exception e) {
        }    
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HacerPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HacerPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HacerPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HacerPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HacerPedido().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaJuegosSeleccionados;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JButton btnVender2;
    private javax.swing.JComboBox<String> cobBanco;
    private javax.swing.JComboBox<String> cobEstado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblHacerPedido;
    private javax.swing.JLabel lblPlataforma;
    private javax.swing.JLabel lblPlataforma1;
    private javax.swing.JLabel lblPlataforma2;
    private javax.swing.JLabel lblPlataforma3;
    private javax.swing.JLabel lblPlataforma4;
    private javax.swing.JLabel lblPlataforma5;
    private javax.swing.JLabel lblPlataforma6;
    private javax.swing.JLabel lblPlataforma7;
    private javax.swing.JLabel lblPlataforma8;
    private javax.swing.JLabel lblPlataforma9;
    private javax.swing.JSpinner spnCantidad2;
    private javax.swing.JTextField txtCalle;
    private javax.swing.JTextField txtColonia;
    private javax.swing.JTextField txtCv;
    private javax.swing.JTextField txtIDJuego2;
    private javax.swing.JTextField txtJuegoSelecionado;
    private javax.swing.JTextField txtMunicipio;
    private javax.swing.JTextField txtNumTarjeta;
    private javax.swing.JTextField txtNumTelefono;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
