/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Clases;

import static Clases.Empleados.res;
import com.sun.glass.events.KeyEvent;
import java.sql.SQLException;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import javax.swing.SpinnerNumberModel;

/**
 *
 * @author mario
 */
public class Salarios extends javax.swing.JFrame {

    /**
     * Creates new form Vender
     */
    
    
    public Salarios() {
        initComponents();
        mostrarSalarios(TablaSalarios, "Select * from vista_salarios");
        
        SpinnerNumberModel modeloSpinner = new SpinnerNumberModel();
        modeloSpinner.setMaximum(2200);
        modeloSpinner.setMinimum(1);
        modeloSpinner.setStepSize(1);
        modeloSpinner.setValue(1);
        spnA.setModel(modeloSpinner);
        spnA2.setModel(modeloSpinner);
        
        SpinnerNumberModel modeloSpinner2 = new SpinnerNumberModel();
        modeloSpinner2.setMaximum(31);
        modeloSpinner2.setMinimum(1);
        modeloSpinner2.setStepSize(1);
        modeloSpinner2.setValue(1);
        spnDia.setModel(modeloSpinner2);
        spnDia2.setModel(modeloSpinner2);
        
        SpinnerNumberModel modeloSpinner3 = new SpinnerNumberModel();
        modeloSpinner3.setMaximum(2200);
        modeloSpinner3.setMinimum(1);
        modeloSpinner3.setStepSize(1);
        modeloSpinner3.setValue(1);
        spnA2.setModel(modeloSpinner3);
        
        SpinnerNumberModel modeloSpinner4 = new SpinnerNumberModel();
        modeloSpinner4.setMaximum(31);
        modeloSpinner4.setMinimum(1);
        modeloSpinner4.setStepSize(1);
        modeloSpinner4.setValue(1);
        spnDia2.setModel(modeloSpinner4);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        lblVender = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaSalarios = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        lblPrecio = new javax.swing.JLabel();
        spnSalario = new javax.swing.JSpinner();
        btnRegresar = new javax.swing.JButton();
        txtIdEmpleado = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblPlataforma5 = new javax.swing.JLabel();
        lblCantidad5 = new javax.swing.JLabel();
        spnA = new javax.swing.JSpinner();
        cobMes = new javax.swing.JComboBox<>();
        spnDia = new javax.swing.JSpinner();
        spnA2 = new javax.swing.JSpinner();
        cobMes2 = new javax.swing.JComboBox<>();
        spnDia2 = new javax.swing.JSpinner();
        btnAgregar = new javax.swing.JButton();
        btnCambiar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(79, 242, 222));
        jPanel3.setForeground(new java.awt.Color(79, 242, 222));

        lblVender.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblVender.setForeground(new java.awt.Color(255, 255, 255));
        lblVender.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblVender.setText("Salarios");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblVender, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblVender, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        TablaSalarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Emp no:", "Salario", "From_date", "To_date"
            }
        ));
        TablaSalarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaSalariosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TablaSalarios);
        if (TablaSalarios.getColumnModel().getColumnCount() > 0) {
            TablaSalarios.getColumnModel().getColumn(0).setResizable(false);
        }

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lblPrecio.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        lblPrecio.setText("Salario:");

        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        txtIdEmpleado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtIdEmpleadoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtIdEmpleadoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIdEmpleadoKeyTyped(evt);
            }
        });

        jLabel4.setText("Emp no:");

        jLabel5.setText("----------------------------------------------------------------------------------------------------------------------------------------------");

        lblPlataforma5.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        lblPlataforma5.setText("De la fecha AAAA/MM/DD:");

        lblCantidad5.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        lblCantidad5.setText("Hasta la fecha AAAA/MM/DD:");

        cobMes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));

        cobMes2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnCambiar.setText("Modificar");
        btnCambiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCambiarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(btnAgregar)
                        .addGap(10, 10, 10)
                        .addComponent(btnCambiar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBuscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEliminar))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(211, 211, 211)
                                .addComponent(lblPrecio)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(spnSalario, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addComponent(spnA, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cobMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(spnDia, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(btnLimpiar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRegresar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(txtIdEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(lblPlataforma5)))
                .addContainerGap(14, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblCantidad5)
                        .addGap(90, 90, 90))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(spnA2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cobMes2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)
                        .addComponent(spnDia2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIdEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCantidad5)
                            .addComponent(lblPlataforma5, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(spnSalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblPrecio)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spnDia2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(spnA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cobMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(spnDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(spnA2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cobMes2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRegresar)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAgregar)
                            .addComponent(btnCambiar)
                            .addComponent(btnEliminar)
                            .addComponent(btnLimpiar)
                            .addComponent(btnBuscar))
                        .addContainerGap(33, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIdEmpleadoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdEmpleadoKeyReleased
        
        if(txtIdEmpleado.getText().isEmpty() && evt.getKeyCode()==KeyEvent.VK_BACKSPACE){
            
            evt.consume();
        }else{
           mostrarSalarios(TablaSalarios, "Select * from vista_salarios where emp_no =" + txtIdEmpleado.getText() + ";"); 
        }
        
    }//GEN-LAST:event_txtIdEmpleadoKeyReleased

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnCambiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCambiarActionPerformed
        try {
            if(spnSalario.getValue().equals(0)){
                JOptionPane.showMessageDialog(this, "No olvides ingresar el salario", "Atencion!!!!", JOptionPane.INFORMATION_MESSAGE);
            }else if(cobMes.getSelectedItem().equals("Seleccionar mes") || spnA.getValue().equals(0) || spnDia.getValue().equals(0)){
                JOptionPane.showMessageDialog(this, "No olvides ingresar la fecha de inicio", "Atencion!!!!", JOptionPane.INFORMATION_MESSAGE);
            }else if(cobMes2.getSelectedItem().equals("Seleccionar mes")|| spnA2.getValue().equals(0) || spnDia2.getValue().equals(0)){
                JOptionPane.showMessageDialog(this, "No olvides ingresar la fecha de finalizacion", "Atencion!!!!", JOptionPane.INFORMATION_MESSAGE);
            }else{
                JOptionPane.showMessageDialog(this, "Modificacion completada!!!");
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnCambiarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        
            if(txtIdEmpleado.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "No olvides ingresar el titulo del juego", "Atencion!!!!", JOptionPane.INFORMATION_MESSAGE);
            }else{
                
                
                
                mostrarSalarios(TablaSalarios, "Select * from vista_salarios");
                txtIdEmpleado.setText("");

                JOptionPane.showMessageDialog(this, "El empleado se a dado de baja");
            }
        
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        metodoRestablecer();
        mostrarSalarios(TablaSalarios, "Select * from vista_salarios");
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        
        mostrarSalarios(TablaSalarios, "Select * from vista_salarios where salary = " + spnSalario.getValue() + 
                                       "OR from_date = '" +spnA.getValue().toString()+ "-" + cobMes.getSelectedItem().toString() + "-" + spnDia.getValue().toString() +
                                       "' OR to_date = '" +spnA2.getValue().toString()+ "-" + cobMes2.getSelectedItem().toString() + "-" + spnDia2.getValue().toString() + "';");
        
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void TablaSalariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaSalariosMouseClicked
        
        metodoRestablecer();
        
        int col = TablaSalarios.getSelectedRow();
        txtIdEmpleado.setText(TablaSalarios.getValueAt(col, 0).toString());
        spnSalario.setValue(Integer.parseInt(TablaSalarios.getValueAt(col, 1)+""));
        spnDia.setValue(Integer.parseInt((TablaSalarios.getValueAt(col, 2)+"").substring(8, 10)));
        spnDia2.setValue(Integer.parseInt((TablaSalarios.getValueAt(col, 3)+"").substring(8, 10)));
        spnA.setValue(Integer.parseInt((TablaSalarios.getValueAt(col, 2)+"").substring(0, 4)));
        spnA2.setValue(Integer.parseInt((TablaSalarios.getValueAt(col, 3)+"").substring(0, 4)));
        
        int mes = 0;
        
        if((TablaSalarios.getValueAt(col, 2)+"").substring(5, 7).equals("01")) {
            mes = 0;
	}else if((TablaSalarios.getValueAt(col, 2)+"").substring(5, 7).equals("02")) {
            mes = 1;
	}else if((TablaSalarios.getValueAt(col, 2)+"").substring(5, 7).equals("03")) {
            mes = 2;
	}else if((TablaSalarios.getValueAt(col, 2)+"").substring(5, 7).equals("04")) {
            mes = 3;
	}else if((TablaSalarios.getValueAt(col, 2)+"").substring(5, 7).equals("05")) {
            mes = 4;
	}else if((TablaSalarios.getValueAt(col, 2)+"").substring(5, 7).equals("06")) {
            mes = 5;
	}else if((TablaSalarios.getValueAt(col, 2)+"").substring(5, 7).equals("07")) {
            mes = 6;
	}else if((TablaSalarios.getValueAt(col, 2)+"").substring(5, 7).equals("08")) {
            mes = 7;
	}else if((TablaSalarios.getValueAt(col, 2)+"").substring(5, 7).equals("09")) {
            mes = 8;
	}else if((TablaSalarios.getValueAt(col, 2)+"").substring(5, 7).equals("10")) {
            mes = 9;
	}else if((TablaSalarios.getValueAt(col, 2)+"").substring(5, 7).equals("11")) {
            mes = 10;
	}else if((TablaSalarios.getValueAt(col, 2)+"").substring(5, 7).equals("12")) {
            mes = 11;
	}
        
        cobMes.setSelectedIndex(mes);
        
        int mes2 = 0;
        
        if((TablaSalarios.getValueAt(col, 3)+"").substring(5, 7).equals("01")) {
            mes2 = 0;
	}else if((TablaSalarios.getValueAt(col, 3)+"").substring(5, 7).equals("02")) {
            mes2 = 1;
	}else if((TablaSalarios.getValueAt(col, 3)+"").substring(5, 7).equals("03")) {
            mes2 = 2;
	}else if((TablaSalarios.getValueAt(col, 3)+"").substring(5, 7).equals("04")) {
            mes2 = 3;
	}else if((TablaSalarios.getValueAt(col, 3)+"").substring(5, 7).equals("05")) {
            mes2 = 4;
	}else if((TablaSalarios.getValueAt(col, 3)+"").substring(5, 7).equals("06")) {
            mes2 = 5;
	}else if((TablaSalarios.getValueAt(col, 3)+"").substring(5, 7).equals("07")) {
            mes2 = 6;
	}else if((TablaSalarios.getValueAt(col, 3)+"").substring(5, 7).equals("08")) {
            mes2 = 7;
	}else if((TablaSalarios.getValueAt(col, 3)+"").substring(5, 7).equals("09")) {
            mes2 = 8;
	}else if((TablaSalarios.getValueAt(col, 3)+"").substring(5, 7).equals("10")) {
            mes2 = 9;
	}else if((TablaSalarios.getValueAt(col, 3)+"").substring(5, 7).equals("11")) {
            mes2 = 10;
	}else if((TablaSalarios.getValueAt(col, 3)+"").substring(5, 7).equals("12")) {
            mes2 = 11;
	}
        
        cobMes2.setSelectedIndex(mes2);
        
    }//GEN-LAST:event_TablaSalariosMouseClicked

    private void txtIdEmpleadoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdEmpleadoKeyTyped
        char validar = evt.getKeyChar();
        
        if(Character.isLetter(validar)){
            getToolkit().beep();
            evt.consume();
            
            JOptionPane.showMessageDialog(rootPane, "Ingresa solo numeros");
        }else if(!(Character.isLetterOrDigit(validar)) &&  !(Character.isWhitespace(validar)) &&  !(evt.getKeyChar()==KeyEvent.VK_BACKSPACE)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Ingresa solo letras");
        }else if(Character.isWhitespace(validar)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "En este apartado no puedes ingresar espacios en blanco");
        }
    }//GEN-LAST:event_txtIdEmpleadoKeyTyped

    private void txtIdEmpleadoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdEmpleadoKeyPressed

    }//GEN-LAST:event_txtIdEmpleadoKeyPressed

     public void mostrarSalarios(JTable tabla,String com){
        DefaultTableModel modelo = (DefaultTableModel) tabla.getModel();
        modelo.setRowCount(0);
        res=Conexiones.Conexion.Consulta(com);
        try {
            
            while(res.next()){
                Vector v = new Vector();
                v.add(res.getInt(1));
                v.add(res.getInt(2));
                v.add(res.getString(3));
                v.add(res.getString(4));
                modelo.addRow(v);
                tabla.setModel(modelo);
            }
                
        } catch (Exception e) {
        }    
    }
    public void metodoRestablecer() {
        
        txtIdEmpleado.setText("");
        cobMes.setSelectedIndex(0);
	cobMes2.setSelectedIndex(0);
        spnSalario.setValue(1);
        spnDia.setValue(1);
        spnDia2.setValue(1);
        spnA.setValue(1);
        spnA2.setValue(1);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Salarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Salarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Salarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Salarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Salarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaSalarios;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCambiar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JComboBox<String> cobMes;
    private javax.swing.JComboBox<String> cobMes2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCantidad5;
    private javax.swing.JLabel lblPlataforma5;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JLabel lblVender;
    private javax.swing.JSpinner spnA;
    private javax.swing.JSpinner spnA2;
    private javax.swing.JSpinner spnDia;
    private javax.swing.JSpinner spnDia2;
    private javax.swing.JSpinner spnSalario;
    private javax.swing.JTextField txtIdEmpleado;
    // End of variables declaration//GEN-END:variables

}
